export const INVOKE = [
  'window:minimize',
  'window:maximize',
  'window:close',
  'window:isMaximized',
  'window:new',
  'window:newPrivate',
  'tabs:create',
  'tabs:close',
  'tabs:activate',
  'tabs:reorder',
  'tabs:duplicate',
  'tabs:pin',
  'tabs:restore',
  'nav:go',
  'nav:back',
  'nav:forward',
  'nav:reload',
  'nav:hardReload',
  'nav:stop',
  'nav:home',
  'omnibox:interpret',
  'omnibox:suggest',
  'find:open',
  'find:close',
  'find:query',
  'find:next',
  'find:prev',
  'zoom:in',
  'zoom:out',
  'zoom:reset',
  'bookmark:toggle',
  'bookmark:list',
  'bookmark:add',
  'bookmark:remove',
  'bookmark:update',
  'bookmark:move',
  'bookmark:search',
  'history:list',
  'history:search',
  'history:delete',
  'history:clear',
  'downloads:pause',
  'downloads:resume',
  'downloads:cancel',
  'downloads:open',
  'downloads:show',
  'downloads:clear',
  'settings:get',
  'settings:set',
  'settings:open',
  'profile:list',
  'profile:switch',
  'profile:create',
  'permission:respond',
  'devtools:open',
  'fullscreen:toggle',
  'clear:data',
  'defaultBrowser:set',
  'defaultBrowser:is',
  'extensions:list',
  'extensions:load',
  'extensions:remove',
  'extensions:setEnabled',
  'updates:check',
  'updates:download',
  'updates:install',
  'pages:state',
  'about:info',
  'chrome:state'
] as const

export const EVENTS = [
  'chrome:state',
  'downloads:changed',
  'find:result',
  'theme:changed',
  'permission:prompt'
] as const

export type InvokeChannel = (typeof INVOKE)[number]
export type EventChannel = (typeof EVENTS)[number]
