
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_BOARD_PLATFORM := aurelia_soc
TARGET_BOOTLOADER_BOARD_NAME := aurelia_phone
BOARD_FLASH_BLOCK_SIZE := 4096
PRODUCT_FULL_TREBLE_OVERRIDE := true

