import React,{useEffect,useState} from 'react';import {View,Text,FlatList,Pressable,TextInput,StyleSheet,KeyboardAvoidingView,Platform,Alert,Clipboard,Image} from 'react-native';import * as ImagePicker from 'expo-image-picker';import * as DocumentPicker from 'expo-document-picker';import {Ionicons} from '@expo/vector-icons';import {useTheme} from '../theme';import {useAuth} from '../store/AuthContext';import {api,uploadAttachment} from '../services/api';import {getSocket} from '../services/socket';import type {Message,User} from '../types';import Avatar from '../components/Avatar';
export default function ChatScreen({route,navigation}:any){const t=useTheme();const {user}=useAuth();const {conversationId,otherUser}:{conversationId:string;otherUser:User}=route.params;const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [typing,setTyping]=useState(false);const [reply,setReply]=useState<Message|null>(null);const s=getSocket();
useEffect(()=>{(async()=>{try{const d=await api<{messages:Message[]}>(`/api/conversations/${conversationId}/messages`);setMessages(d.messages);await api(`/api/conversations/${conversationId}/read`,{method:'POST'})}catch{}})();s.emit('conversation:join',conversationId);const on=(m:Message)=>{if(m.conversationId===conversationId){setMessages(x=>x.some(a=>a.id===m.id)?x:[...x,m]);if(m.senderId!==user?.id)s.emit('message:delivered',m.id)}};const del=(d:any)=>setMessages(x=>x.filter(m=>m.id!==d.messageId));const rec=(d:any)=>setMessages(x=>x.map(m=>m.id===d.messageId?{...m,...(d.status==='read'?{readAt:new Date().toISOString(),deliveredAt:m.deliveredAt||new Date().toISOString()}:{deliveredAt:new Date().toISOString()})}:m));const typ=(d:any)=>{if(d.conversationId===conversationId&&d.userId!==user?.id)setTyping(d.typing)};s.on('message:new',on);s.on('message:deleted',del);s.on('message:receipt',rec);s.on('typing',typ);return()=>{s.emit('conversation:leave',conversationId);s.off('message:new',on);s.off('message:deleted',del);s.off('message:receipt',rec);s.off('typing',typ)}},[conversationId]);
const send=()=>{const body=text.trim();if(!body)return;s.emit('message:send',{conversationId,body,messageType:'text',replyToMessageId:reply?.id||null},(r:any)=>{if(!r?.ok)Alert.alert('Send failed',r?.error||'Unknown error');});setText('');setReply(null)};
const attach=async()=>{try{const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.85});if(!result.canceled){const a=result.assets[0];const up=await uploadAttachment(a.uri,a.fileName||`image-${Date.now()}.jpg`,a.mimeType||'image/jpeg',conversationId);s.emit('message:send',{conversationId,messageType:'image',attachmentUrl:up.attachment.url,attachmentName:up.attachment.name});}}catch(e:any){Alert.alert('Attachment',e.message)}};
const file=async()=>{try{const r=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true});if(!r.canceled){const a=r.assets[0];const up=await uploadAttachment(a.uri,a.name,a.mimeType||'application/octet-stream',conversationId);s.emit('message:send',{conversationId,messageType:'file',attachmentUrl:up.attachment.url,attachmentName:up.attachment.name});}}catch(e:any){Alert.alert('Attachment',e.message)}};
const remove=(m:Message)=>Alert.alert('Message options',undefined,[{text:'Reply',onPress:()=>setReply(m)},{text:'Copy',onPress:()=>m.body&&Clipboard.setString(m.body)},{text:'Delete',style:'destructive',onPress:()=>s.emit('message:delete',m.id)},{text:'Cancel',style:'cancel'}]);
return <KeyboardAvoidingView style={{flex:1,backgroundColor:t.bg}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={[s.head,{borderBottomColor:t.line}]}><Pressable onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={28} color={t.text}/></Pressable><Avatar name={otherUser.displayName} url={otherUser.avatarUrl} size={40}/><View style={{flex:1,marginLeft:10}}><Text style={[s.name,{color:t.text}]}>{otherUser.displayName}</Text><Text style={{color:typing?t.accent:t.muted,fontSize:12}}>{typing?'typing…':`@${otherUser.username}`}</Text></View></View>
<FlatList data={messages} keyExtractor={x=>x.id} contentContainerStyle={{padding:16,paddingBottom:18}} renderItem={({item})=>{const mine=item.senderId===user?.id;return <Pressable onLongPress={()=>remove(item)} onPress={()=>item.body&&Clipboard.setString(item.body)} style={[s.bubble,{backgroundColor:mine?t.accent:t.card,alignSelf:mine?'flex-end':'flex-start',borderColor:t.line}]}>{item.messageType==='image'&&item.attachmentUrl?<Image source={{uri:`${require('../services/config').API_URL}${item.attachmentUrl}`}} style={s.image}/> : <Text style={{color:mine?'#fff':t.text,fontSize:16}}>{item.body||item.attachmentName||'[Attachment]'}</Text>}<Text style={{color:mine?'#DCEAFF':t.muted,fontSize:10,marginTop:5}}>{new Date(item.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} {mine?(item.readAt?'✓✓':item.deliveredAt?'✓':''):''}</Text></Pressable>}}/>
{reply&&<View style={{paddingHorizontal:14,paddingVertical:8,backgroundColor:t.card,borderTopWidth:1,borderColor:t.line}}><Text style={{color:t.muted}}>Replying to: {reply.body}</Text></View>}
<View style={[s.compose,{borderTopColor:t.line,backgroundColor:t.card}]}><Pressable onPress={attach}><Ionicons name="image-outline" size={24} color={t.accent}/></Pressable><Pressable onPress={file}><Ionicons name="attach-outline" size={24} color={t.accent}/></Pressable><TextInput value={text} onChangeText={x=>{setText(x);s.emit(x?'typing:start':'typing:stop',conversationId)}} onBlur={()=>s.emit('typing:stop',conversationId)} placeholder="Message" placeholderTextColor={t.muted} style={[s.input,{backgroundColor:t.input,color:t.text}]}/><Pressable onPress={send} style={[s.send,{backgroundColor:t.accent}]}><Ionicons name="arrow-up" size={20} color="#fff"/></Pressable></View></KeyboardAvoidingView>}
const s=StyleSheet.create({head:{height:64,borderBottomWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:8},name:{fontWeight:'800',fontSize:16},image:{width:220,height:220,borderRadius:12},bubble:{maxWidth:'82%',borderWidth:1,borderRadius:18,padding:12,marginBottom:9},compose:{padding:9,gap:8,flexDirection:'row',alignItems:'center',borderTopWidth:1},input:{flex:1,borderRadius:22,paddingHorizontal:16,paddingVertical:10,fontSize:16},send:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'}});
